(define (square x) (* x x))

(define (f a b c) (if (> a b)
		      (if (> b c)
			  (+ (square a) (square b))
			  (+ (square a) (square c))
			  )
		      (if (> a c)
			  (+ (square a) (square b))
			  (+ (square b) (square c))
			  )
		      ))
;; test casesshould return 13
(f 1 2 3)
(f 1 3 2)
(f 2 1 3)
(f 2 3 1)
(f 3 2 1)
(f 3 1 2)
